#!/bin/bash

while true
do
line="----------\nBRANCH\n----------\n$(git branch)\n\n"
line="$line----------\nSTATUS\n----------\n$(git status -s)\n\n"
line="$line----------\nLOG\n----------\n$(git log --pretty=format:'%h - %s' --graph -n $1)"
clear
echo -e "$line"
sleep 5
done
