version: '3'
services:

  # Proxy management
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./caddyfile:/etc/Caddyfile
      - $HOME/.docker/caddy:/root/.caddy
    # restart: always
    ports:
      - '80:80'
      - '443:443'

  # DNS for https://domains.google.com
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    # Configs stored outside of repo
    volumes:
      - $HOME/.docker/caddy/ddclient:/config
    labels:
      com.ouroboros.enable: "true"
    # restart: unless-stopped
