#!/bin/bash

# TODO (160721) - This shuold be replaced by/moved to the dotfiles repo

#----------------------------------------------------------------------------------------------------
# Workspaces
#----------------------------------------------------------------------------------------------------

# Workspace size
col=2	# Number of columns in 'workspace'
row=2	# Number of rows in 'workspace'

# Set 'hsize' and 'vsize' (will automatically enable 'workspace')
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize $col
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize $row

#----------------------------------------------------------------------------------------------------
# fstab
#----------------------------------------------------------------------------------------------------

#--------------------------------------------------
# fstab_write
# desc: Write new mount to fstab without
#		overwriting the existing entries.
#--------------------------------------------------
# Write new mount to fstab, will not overwrite existing
function fstab_write {
# Count entries existing in 'fstab'
count=$(grep -c "$1" /etc/fstab)			# Count entries existing in 'fstab'

# Map new servers to fstab
if [ $count -eq 0 ]; then					# Confirm mount does not exist
	sudo echo -e "\n# $1\n$2" >> /etc/fstab	# Write mounting information to 'fstab'

else										# Server already mapped
	echo "Host name '$1' is already mapped"	# Display error for user
fi
exit										# Exit function
}

# Make required 'mount' dir(s)
sudo mkdir -p /mnt/nas		# 'tjg-nas'
sudo mkdir -p /mnt/rne		# 'rne-server'
sudo mkdir -p /mnt/dlink	# 'rne-dlink'

# Backup existing 'fstab'
sudo mkdir -p /etc/fstab-backups									# Create backup dir if required
sudo cp /etc/fstab /etc/fstab-backups/fstab-$(date +%y%m%d_%H%M%S)	# Copy and timestamp cur 'fstab'

# Add mounting information for each of the servers (see 'fstab_write')
fstab_write "tjg-nas" "//192.168.228.100/storage/usb1_1\t/mnt/nas\tcifs\tguest,uid=1000,iocharset=utf8\t0\t0"
fstab_write "rne-server" "//192.168.227.12/rne\t/mnt/rne\tcifs\tsec=ntlm,username=travis.gall,password=1987tJg20,iocharset=utf8,dir_mode=0770,noperm,noauto\t0\t0"
fstab_write "rne-dlink" "//192.168.227.2/Volume_1\t/mnt/dlink\tcifs\tsec=ntlm,username=user,password=user123$,iocharset=utf8,noauto\t0\t0"

#----------------------------------------------------------------------------------------------------
# Hosts
#----------------------------------------------------------------------------------------------------

# 'Hosts' files and directories
hosts="/etc/hosts"											# 'Hosts' file
hosts_backup="/etc/hosts-backups"							# Backup dir

# Backup
sudo mkdir -p $hosts_backup									# Create backup dir
sudo cp $hosts $hosts_backup/hosts-$(date +%y%m%d_%H%M%S)	# Copy and timestamp cur 'hosts'

# Create and add new host
name="tc"													# New host 'tc'
addr="96.53.22.134"											# New host '96.53.22.134'
sudo echo -e "\n$addr\t$name" >> $hosts						# Add new host

# Apply modifications
sudo /etc/init.d/networking restart							# Restart network and apply


